version: '2'

services:
  db:
    image: redis:3.0.7-alpine
    container_name: db
    volumes:
      - ./data-db:/data
    expose:
      - 6379
    #ports:
    #- "6379:6379"

  tracker:
    build: ./tracker/
    container_name: tracker
    depends_on:
      - db
    ports:
      - "80:80"

  broadcaster:
    build: ./broadcaster/
    container_name: broadcaster
    depends_on:
      - db
    ports:
      - "8080:8080"

  target:
    image: warcforceone/ateam-airsync
    container_name: target
    environment:
      - DISK_HARD_LIMIT=96
      - DISK_LIMIT=94
      - MAX_CONN=125
    volumes:
      - ./data-target:/data
    ports:
      - "873:873"

  grab:
    build: load-grab
    #container_name: grab  #comment out container naming to use docker-compose scaling
